# Site settings
title: PJC
email: me@pjchung.github.io  
description: "Personal website of PJC"
baseurl: ""
url: "http://pjchung.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Excludes
exclude:
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - node_modules/
  - package.json
  - Rakefile
  - README.md
  - bower.json
